# Generated by Django 2.1.2 on 2018-10-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('bid_price', models.IntegerField()),
                ('winning_bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=1000)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('base_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('user_image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Users'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Users'),
        ),
        migrations.AddField(
            model_name='bids',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Products'),
        ),
    ]
