# Generated by Django 2.1.2 on 2018-10-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
