# Generated by Django 2.1.2 on 2018-10-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20181013_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='winning_bid',
            field=models.IntegerField(blank=True),
        ),
    ]
