# Generated by Django 2.1.2 on 2018-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20181013_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winning_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='is_winning',
            field=models.BooleanField(default=False),
        ),
    ]
